#
# Fastfile
# Copyright © 2019 Netguru S.A. All rights reserved.
#

# Fastlane will make sure that the `highway` gem is loaded and will display
# useful information if it's not.

fastlane_require "highway"

desc "Run Highway."
lane :highway do |options|

  # Use the same behavior of computing option values as in action entry point.
  # First, get the actual values, then fall back to env variables, then fall
  # back to default values.

  path = options[:highwayfile]
  path ||= ENV["HIGHWAY_HIGHWAYFILE"]
  path ||= "Highwayfile.yml"

  preset = options[:preset]
  preset ||= ENV["HIGHWAY_PRESET"]
  preset ||= "default"

  # Run Highway from `:lane` entry point.

  main = Highway::Main.new(
    entrypoint: :lane,
    path: path,
    preset: preset,
    fastlane_runner: runner,
    fastlane_lane_context: lane_context,
  )

  main.run()

end
